-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 19:58:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BloodDonationDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BloodDonationDB` ;

-- -----------------------------------------------------
-- Schema BloodDonationDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BloodDonationDB` DEFAULT CHARACTER SET utf8 ;
USE `BloodDonationDB` ;

-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Donors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Donors` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Donors` (
  `name` VARCHAR(45) NOT NULL,
  `blood_type` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `amount` INT NOT NULL,
  `donorID` INT NOT NULL,
  PRIMARY KEY (`donorID`, `name`),
  UNIQUE INDEX `donorID_UNIQUE` (`donorID` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`BloodBank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`BloodBank` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`BloodBank` (
  `donorCount` INT NOT NULL,
  `inventory` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location`),
  INDEX `BLOODBANK_DONORS_FK_idx` (`donorCount` ASC) VISIBLE,
  CONSTRAINT `BLOODBANK_DONORS_FK`
    FOREIGN KEY (`donorCount`)
    REFERENCES `BloodDonationDB`.`Donors` (`donorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Patients` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Patients` (
  `name` VARCHAR(50) NOT NULL,
  `blood_type` VARCHAR(50) NOT NULL,
  `DOB` DATE NOT NULL,
  `PatientID` INT NOT NULL,
  PRIMARY KEY (`name`, `blood_type`, `PatientID`),
  UNIQUE INDEX `PatientID_UNIQUE` (`PatientID` ASC) VISIBLE,
  UNIQUE INDEX `blood_type_UNIQUE` (`blood_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Hospitals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Hospitals` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Hospitals` (
  `patientCount` INT NOT NULL,
  `inventory` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location`),
  INDEX `HOSPITALS_PATIENT_FK_idx` (`patientCount` ASC) VISIBLE,
  CONSTRAINT `HOSPITALS_PATIENT_FK`
    FOREIGN KEY (`patientCount`)
    REFERENCES `BloodDonationDB`.`Patients` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Medical_Personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Medical_Personnel` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Medical_Personnel` (
  `name` INT NOT NULL,
  `occupied` VARCHAR(50) NOT NULL,
  `assigned` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `MEDICALPERSONNEL_HOSPITAL_FK_idx` (`assigned` ASC) VISIBLE,
  CONSTRAINT `MEDICALPERSONNEL_HOSPITAL_FK`
    FOREIGN KEY (`assigned`)
    REFERENCES `BloodDonationDB`.`Hospitals` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MEDICALPERSONNEL_BLOODBANK_FK`
    FOREIGN KEY (`assigned`)
    REFERENCES `BloodDonationDB`.`BloodBank` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Medical_Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Medical_Information` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Medical_Information` (
  `name` VARCHAR(50) NOT NULL,
  `blood_type` VARCHAR(15) NOT NULL,
  `donor_patient` VARCHAR(10) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Location` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Location` (
  `idLocation` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address`),
  CONSTRAINT `LOCATION_HOSPITAL_FK`
    FOREIGN KEY (`address`)
    REFERENCES `BloodDonationDB`.`Hospitals` (`location`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LOCATION_BLOODBANK_FK`
    FOREIGN KEY (`address`)
    REFERENCES `BloodDonationDB`.`BloodBank` (`location`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Supervisor` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Supervisor` (
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  INDEX `SUPERVISOR_BLOODBANK_FK_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `SUPERVISOR_HOSPITAL_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`Hospitals` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SUPERVISOR_BLOODBANK_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`BloodBank` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Exam` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Exam` (
  `idExam` INT NOT NULL,
  `passed` VARCHAR(10) NOT NULL,
  `length` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  CONSTRAINT `EXAM_DONOR_FK`
    FOREIGN KEY (`idExam`)
    REFERENCES `BloodDonationDB`.`Donors` (`donorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EXAM_PATIENT_FK`
    FOREIGN KEY (`idExam`)
    REFERENCES `BloodDonationDB`.`Patients` (`PatientID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Blood_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Blood_type` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Blood_type` (
  `blood_type` VARCHAR(50) NOT NULL,
  `amount` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `blood_type_UNIQUE` (`blood_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Reception`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Reception` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Reception` (
  `name` VARCHAR(50) NOT NULL,
  `occupied` VARCHAR(10) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `RECEPTION_BLOODBANK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`BloodBank` (`location`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RECEPTION_HOSPITAL_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`Hospitals` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Incentive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Incentive` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Incentive` (
  `amount` INT NOT NULL,
  `inventive_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`inventive_id`),
  UNIQUE INDEX `inventive_id_UNIQUE` (`inventive_id` ASC) VISIBLE,
  INDEX `INCENTIVE_BLOODBANK_FK_idx` (`amount` ASC) VISIBLE,
  CONSTRAINT `INCENTIVE_BLOODBANK_FK`
    FOREIGN KEY (`amount`)
    REFERENCES `BloodDonationDB`.`BloodBank` (`donorCount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Inventory` (
  `amount` INT NOT NULL,
  `blood_type` VARCHAR(45) NULL,
  `stock` INT NOT NULL,
  INDEX `INVENTORY_BLOODTYPE_FK_idx` (`blood_type` ASC) VISIBLE,
  CONSTRAINT `INVENTORY_BLOODTYPE_FK`
    FOREIGN KEY (`blood_type`)
    REFERENCES `BloodDonationDB`.`Blood_type` (`blood_type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`BloodBags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`BloodBags` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`BloodBags` (
  `blood_type` VARCHAR(45) NULL,
  `amount` INT NOT NULL,
  `bag_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`bag_id`),
  INDEX `BLOODBAG_BLOODTYPE_FK_idx` (`blood_type` ASC) VISIBLE,
  CONSTRAINT `BLOODBAG_BLOODTYPE_FK`
    FOREIGN KEY (`blood_type`)
    REFERENCES `BloodDonationDB`.`Blood_type` (`blood_type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Medical_device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Medical_device` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Medical_device` (
  `idMedical_device` INT NOT NULL,
  `amount` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedical_device`),
  CONSTRAINT `MEDICALDEVICE_MEDICALPERSONNEL_FK`
    FOREIGN KEY (`idMedical_device`)
    REFERENCES `BloodDonationDB`.`Medical_Personnel` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`WalkIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`WalkIN` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`WalkIN` (
  `name` VARCHAR(50) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `WALKIN_PATIENT_FK_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `WALKIN_PATIENT_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`Patients` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Request` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Request` (
  `request_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `REQUEST_DONOR_FK`
    FOREIGN KEY (`request_id`)
    REFERENCES `BloodDonationDB`.`Donors` (`donorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `REQUEST_PATIENT_FK`
    FOREIGN KEY (`request_id`)
    REFERENCES `BloodDonationDB`.`Patients` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Insurance` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Insurance` (
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `covered` TINYINT NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `INSURANCE_PATIENT_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`Patients` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `INSURANCE_DONOR_FK`
    FOREIGN KEY (`name`)
    REFERENCES `BloodDonationDB`.`Donors` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationDB`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationDB`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `BloodDonationDB`.`Appointment` (
  `date` DATE NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `APPOINTMENT_DONOR_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `BloodDonationDB`.`Donors` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `APPOINTMENT_PATIENT_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `BloodDonationDB`.`Patients` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
